version: '3.8'

services:
  dns_server:
    build:
        context: .
        dockerfile: docker/Dockerfile
    privileged: true
    volumes:
      - ./server.py:/elocal/server.py
    ports:
      - "49152:49152/udp"
    restart: always
    container_name: local_dns_resolver_for_socks
