version: '3.8'

services:
  dns_server:
    build:
        context: .
        dockerfile: docker/Dockerfile
    privileged: true
    volumes:
      - ./main.py:/elocal/main.py
      - ./adservers.txt:/elocal/adservers.txt
      - ./facebook.txt:/elocal/facebook.txt
    ports:
      - "53:53/udp"
    command: bash -c "cd /elocal && python3 -u main.py"
    restart: always
    container_name: local_dns_resolver
